/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mwypych' at '24.11.16 12:27' with Gradle 3.1
 *
 * @author mwypych, @date 24.11.16 12:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
